
//----------------------------------------------------
// The following code was generated by CUP-WIT v1.0
//----------------------------------------------------

package java_cup.core;

public interface Tokens {

    /* terminals */
    int EOF = 0;
    int ERROR = 1;
    int PACKAGE = 2;
    int IMPORT = 3;
    int SUPER = 4;
    int EXTENDS = 5;
    int TERMINAL = 6;
    int NONTERMINAL = 7;
    int PRECEDENCE = 8;
    int NONASSOC = 9;
    int PERCENT_PREC = 10;
    int SEMI = 11;
    int COMMA = 12;
    int COLON = 13;
    int COLON_COLON_EQUALS = 14;
    int BAR = 15;
    int LEFT = 16;
    int RIGHT = 17;
    int LBRACK = 18;
    int RBRACK = 19;
    int GT = 20;
    int LT = 21;
    int QUESTION = 22;
    int ID = 23;
    int CODE = 24;
    int CLASSNAME = 25;

    /* non terminals */
    //int $START = 0;
    //int start = 1;
    //int pkg = 2;
    //int imports = 3;
    //int varTerms = 4;
    //int prods = 5;
    //int varTerm = 6;
    //int prod = 7;
    //int prodHead = 8;
    //int prodParts = 9;
    //int prodPart = 10;
    //int rhsList = 11;
    //int rhs = 12;
    //int preceds = 13;
    //int preced = 14;
    //int symbolList = 15;
    //int typeName = 16;
    //int robustIdent = 17;
    //int typearglist = 18;
    //int typearguement = 19;
}

