
//----------------------------------------------------
// The following code was generated by CUP-WIT v1.0
//----------------------------------------------------

package java_cup.core;

public interface Tokens {

    /* terminals */
    int EOF = 0;
    int ERROR = 1;
    int PACKAGE = 2;
    int IMPORT = 3;
    int SUPER = 4;
    int EXTENDS = 5;
    int TERMINAL = 6;
    int NONTERMINAL = 7;
    int PRECEDENCE = 8;
    int NONASSOC = 9;
    int PERCENT_PREC = 10;
    int SEMI = 11;
    int COMMA = 12;
    int COLON = 13;
    int COLON_COLON_EQUALS = 14;
    int BAR = 15;
    int LEFT = 16;
    int RIGHT = 17;
    int LBRACK = 18;
    int RBRACK = 19;
    int LPAREN = 20;
    int RPAREN = 21;
    int GT = 22;
    int LT = 23;
    int QUESTION = 24;
    int ID = 25;
    int CODE = 26;
    int CLASSNAME = 27;

    /* non terminals */
    //int $START = 0;
    //int start = 1;
    //int varTerm = 2;
    //int preced = 3;
    //int prodPart = 4;
    //int prodPartSym = 5;
    //int typeName = 6;
    //int robustIdent = 7;
    //int labid = 8;
    //int typearglist = 9;
    //int typearguement = 10;
    //int $IPNT_0 = 11;
    //int $IPNT_0$$opt = 12;
    //int $IPNT_1 = 13;
    //int $IPNT_1$$lst$ = 14;
    //int $IPNT_1$$lst$$$opt = 15;
    //int varTerm$$lst$ = 16;
    //int preced$$lst$ = 17;
    //int preced$$lst$$$opt = 18;
    //int prodPart$$lst$ = 19;
    //int prodPart$$lst$$$lst$BAR = 20;
    //int $IPNT_2 = 21;
    //int $IPNT_2$$lst$ = 22;
    //int ID$$lst$COMMA = 23;
    //int ID$$opt = 24;
    //int labid$$opt = 25;
}

