
//----------------------------------------------------
// The following code was generated by CUP-WIT v1.0
//----------------------------------------------------

package java_cup.core;

public interface Tokens {

    /* terminals */
    int EOF = 0;
    int ERROR = 1;
    int PACKAGE = 2;
    int IMPORT = 3;
    int SUPER = 4;
    int EXTENDS = 5;
    int TERMINAL = 6;
    int NONTERMINAL = 7;
    int PRECEDENCE = 8;
    int NONASSOC = 9;
    int PERCENT_PREC = 10;
    int SEMI = 11;
    int COMMA = 12;
    int COLON = 13;
    int COLON_COLON_EQUALS = 14;
    int BAR = 15;
    int LEFT = 16;
    int RIGHT = 17;
    int LBRACK = 18;
    int RBRACK = 19;
    int GT = 20;
    int LT = 21;
    int QUESTION = 22;
    int ID = 23;
    int CODE = 24;
    int CLASSNAME = 25;

    /* non terminals */
    //int $START = 0;
    //int start = 1;
    //int pkg = 2;
    //int imports = 3;
    //int varTerm = 4;
    //int prod = 5;
    //int prodHead = 6;
    //int prodPart = 7;
    //int rhs = 8;
    //int preced = 9;
    //int typeName = 10;
    //int robustIdent = 11;
    //int labid = 12;
    //int typearglist = 13;
    //int typearguement = 14;
    //int pkg$$opt = 15;
    //int imports$$lst$ = 16;
    //int imports$$lst$$$opt = 17;
    //int varTerm$$lst$ = 18;
    //int preced$$lst$ = 19;
    //int preced$$lst$$$opt = 20;
    //int prod$$lst$ = 21;
    //int ID$$lst$COMMA = 22;
    //int rhs$$lst$BAR = 23;
    //int prodPart$$lst$ = 24;
    //int labid$$opt = 25;
    //int ID$$opt = 26;
}

