#!/bin/bash
cd $(dirname $0)

$JAVA_HOME/bin/java -Dfile.encoding=UTF-8 -jar java_cup_webit-20150303.jar -destdir ../java/java_cup/core -destresdir ../resources/java_cup/core Parser.cup

echo 'Press any to exit...'
read -n 1

